### ISSUE TITLE
Team 23 Review: SRS

### ISSUE THREAD

**Issue by LemonU-mcmaster** [jordanbierbrier/capstone#1]
@samm82

1. NFR12 seems a bit unachievable since for any server applications the best achievable availability in the industry (or so called SLA) is 99.99999%, and for less critical applications the availability is usually between 99.8% and 99.99%
2. NFR23 sounds like a FR since it talks about what the system should be able to do
3. NFR-21 Sounds like a FR since it mentions what the product is expected to do, i.e. interface with mobile devices
4. NFR-25 Seems ambiguous, it mentions "[striving] to include more languages", it should specify in clear terms whether English will be the only supported language or if they intend to support multiple languages
5. Interfacing with a mobile device through bluetooth seems to be a main component of the system and is mentioned throughout the document and depicted in the context diagram however there is no functional requirement that talks about this feature.
6. NFR2 mentions the responsiveness of the buttons and that the process will begin as the button is pressed. The fit criterion seems to also be related to the response from the buttons. This is shouldn't be a style requirement.
7.  For NRF3 It mention's that the user should be able to operate the device for the sample there is little description of this sample group. As well as the age range for the sample group.

**Comment by LemonU-mcmaster** [comment]
For some reason Github does not allow me to choose a label for this issue. I'd assume that one of the collaborators of this repo needs to do the label assignment.

**Comment by jordanbierbrier** [comment]
@LemonU-mcmaster Thank you for the detailed feedback! I have added the label to the issue.

**Comment by smiths** [comment]
@LemonU-mcmaster, next time, please create separate issues.  Separate issues are better for tracking and for closing issues.  This issue can't be closed until all 7  items have been dealt with.

**Comment by UdeepShah** [comment]
Updated NFR 2, 12, 21, 23, and 25.
