### ISSUE TITLE
Team 21 Review: Issues with System Test NFRT29

### ISSUE THREAD

**Issue by purefisher** [jordanbierbrier/capstone#10]
The system test NFRT29 is not very clear. This test states that testers will be given a device to stress test. Stress tests include battery drain, material wear, or extensive microphone use. The test then states that the device should be rated for 5 years of use. This test case is first of all way too long to be tested as a system test. The case also does not explain how much wear and tear should be put on the phone, how often it should be used in the 5 years, etc. This test case should be updated.

**Comment by UdeepShah** [comment]
The team is reviewing the test and is most likely to be removed because it is beyond our project's scope.
