### ISSUE TITLE
Team 20 Review MG: Table 3 is not one to one mapping

### ISSUE THREAD

**Issue by zhul49** [jordanbierbrier/capstone#12]
For the Traceability Matrix between Anticipated Changes and Modules it should show a one to one mapping. Ideally, changing one of the anticipated changes will only require changing the module that hides the associated decision. If that was not possible, for example, with AC5 requiring both Bluetooth connection and communication, there should be an explanation that explains why it is an exception to the rule or recognize that M3 and M9 can be considered as one module.

**Comment by Azriel-Gingoyon** [comment]
We believe that some Requirements/Anticipated Changes do correspond to more than module and thus we have left them as is.
