### ISSUE TITLE
Team 20 Review SystDes: Timeline 

### ISSUE THREAD

**Issue by ChenJiahuiEmily** [jordanbierbrier/capstone#13]
The picture for the timeline can be adjusted to a more readable format, for example, make the font size bigger and change the font colour to a more obvious colour. And each team member's responsibility should be added in this section.

**Comment by Azriel-Gingoyon** [comment]
Font size has been made bigger and font color changed so that text is more clear/visible. 
Furthermore, team member responsibility table has been added in section 10.
