### ISSUE TITLE
Team20 Review MIS: Need more details

### ISSUE THREAD

**Issue by Nafster619** [jordanbierbrier/capstone#14]
Some of the modules seem to be missing a local functions section. Even if the module does not have any local functions, that should be indicated with "N/A". Adding some comments to your environment variables would also make the purpose of the variable more clear and can help anyone trying to recreate the project understand what information is being stored. Also, Adding a hardware hiding module would be beneficial as it would make the communication between the software and hardware a little more clear.

**Comment by Azriel-Gingoyon** [comment]
The modules with no local functions have been indicated with "N/A".
