### ISSUE TITLE
Team 20 MG Review: Redundancy in sections 7.2 and 7.3

### ISSUE THREAD

**Issue by kelhuynh** [jordanbierbrier/capstone#15]
You do not need a general description of what secrets and services are in the behaviour-hiding and software decision module sections. This is because they are not explicitly part of your module hierarchy unlike the subsections (i.e 7.2.x or 7.3.x) under sections 7.2 and 7.3. From a reading perspective, the formatting of behaviour-hiding and software decision modules in terms of what secrets and services are should be self-explanatory. However, you may wish to include the circumstances in which a module's secrets and services may change in a brief blurb under the section heading if desired.

**Comment by Azriel-Gingoyon** [comment]
We believe that the descriptions of the module sections are important for producing complete documentation, so the sections have been kept in. Furthermore, the module circumstances will be kept in mind for future iterations.
