### ISSUE TITLE
Team 20 MIS Review: Missing Table Name

### ISSUE THREAD

**Issue by gordonia157** [jordanbierbrier/capstone#17]
The table in section 2 has no name labeled.

By the way, it would be better if you could keep the indentation rule of paragraphs constant throughout all documents. For example, in MIS document, only the second paragraphs in section 1 and 2 have indentations in their first lines; in SystDes document, the second paragraphs in section 2, section 7.1 and section 7.2 have indentations in their first lines, while all other sections don't have such indentations in their second paragraphs.

**Comment by Taranjit-lotey** [comment]
Tables have been labelled and indents have been removed from 2nd paragraphs
