### ISSUE TITLE
Team 19 VnV Report Review: Nonfunctional Requirement Evaulation

### ISSUE THREAD

**Issue by TommYlw** [jordanbierbrier/capstone#18]
Everything looks good, except for following suggestions:
1. For section 5.1, the "manual" doesn't sound like a non-functional quality, maybe can change to corresponding words such as usability, accessibility etc.
2. In my opinion, stress test should be used a large amount of data etc. For example, for NFRT 25, I am a bit doubt whether using 10 devices is fulfilling the concept of using large amount of data.

**Comment by Taranjit-lotey** [comment]
Fixed the non-functional quality
