### ISSUE TITLE
Team 22 Review Hazard Analysis - Section 5

### ISSUE THREAD

**Issue by qureshe00** [jordanbierbrier/capstone#2]
In the FMEA table for the microphone component, the failure effects could be more descriptive. Instead of saying "device is unable to perform primary function" or "device functions incorrectly" it would be helpful to address exactly what the primary function that fails is, or what the incorrect behaviour is expected to be.  For example, "device is unable to receive/process sound" This way the reader will be able to understand the effect of the failure from the table itself.

**Comment by Azriel-Gingoyon** [comment]
"Device is unable to receive sound" was added to Microphone - Effects of Failure column in Table 1: FMEA
