### ISSUE TITLE
Team 19 VnV Report Review

### ISSUE THREAD

**Issue by MokshaSri** [jordanbierbrier/capstone#22]
Hey, great job on the VnV report! It was easy to follow and read! I had a couple of suggestions:
1. For 7.1, could you add which unit tests resulted in these changes? It would be easy to refer back to that way
2. In the VnV Plan you mentioned the usability survey, if you're still using those questions for appearance, style, ease of use, please add them to the report.

**Comment by Taranjit-lotey** [comment]
1.  Reference to resulted changes are written
2. Out of Scope
