### ISSUE TITLE
 Team 22 Review Hazard Analysis - Missing list of figures and list of tables

### ISSUE THREAD

**Issue by fahmed8383** [jordanbierbrier/capstone#3]
According to the rubric under the content section, a list of figures and tables is also required in table of contents. However since this document only had a single table in it I am not sure how necessary that is despite what the rubric states.

However if in future revision additional tables or figures do need to be added, or simply to make the table easier to find, it may be best to follow the rubrics recommendation on including this.

**Comment by Azriel-Gingoyon** [comment]
List of Tables and List of Figures have both been added to the Hazard Analysis document.
