### ISSUE TITLE
Team 22 Review Hazard Analysis - Section 6 

### ISSUE THREAD

**Issue by KevinRK29** [jordanbierbrier/capstone#4]
@samm82

There are NFRs being used in the FMEA table under the "Safety Requirements" column that aren't specified in Section 6 - Safety and Security Requirements. For example, NFR-8 and NFR-17 both aren't specified in the Safety and Security Requirements section

**Comment by Azriel-Gingoyon** [comment]
Two new safety and security requirements (IR8 and ACR4) with their corresponding descriptions in section 6 have been added in the FMEA tables to replace NFR-8 and NFR-17 respectively.
