### ISSUE TITLE
Team 22 Review Hazard Analysis - Difficult to match recommended action to causes of failures

### ISSUE THREAD

**Issue by fahmed8383** [jordanbierbrier/capstone#5]
For some rows in the table which have multiple causes of failures, the number of recommended actions do not match the causes of failures. Thus, it is difficult to track which recommended action is for which cause, for example for S1-1, by default someone would assume that recommended action 3 is for cause of failure 3, however it is actually for cause of failure 4.

**Comment by Azriel-Gingoyon** [comment]
The FMEA entries have been updated so that the numbered recommended actions will correspond to their respective numbered cause of failure. (Essentially action 1 is for cause 1, etc.)
