### ISSUE TITLE
Team 22 Review Hazard Analysis - Missing Authentication subsystem

### ISSUE THREAD

**Issue by RutheniumVI** [jordanbierbrier/capstone#6]
I noticed through your requirement ACR1 and ACR2, that you guys support authentication for personal accounts. I feel like that should also been a seperate boudary or subsystem of your system that you should have analyzed for hazards. Authentication has a lot points of failures, such as malicous attacks, loss of user information from the database, etc. Those hazards should have been identified too since strengthening the security of you authenticaiton system is very important

@samm82

**Comment by Azriel-Gingoyon** [comment]
Removed authentication/personal account aspects from our project since they were no longer relevant/needed. Have revised information relevant to ACR1 and ACR2 descriptions accordingly.
