### ISSUE TITLE
Team 21 Review: Issues with Objectives

### ISSUE THREAD

**Issue by turek15** [jordanbierbrier/capstone#7]
I've noticed for your objectives section of the VnV plan your missing some key points. Overall your VnV objectives should highlight all the required needs in order to validate and verify the quality of your system. Firstly, you should mention that the testing environment will be specified. This is important because it outlines the context of how the testing will be done. Secondly, instead of mentioning what testing will be done (in this case unit testing) you should more generically specify that the plan will outline all necessary activities and relevant tools in conjuction with the VnV plan.

**Comment by turek15** [comment]
Please add a label for our group

**Comment by UdeepShah** [comment]
Complete review of VnV plan done, altered some test cases to match feedback.
