### ISSUE TITLE
Team 21 Review: Issues with System Test FRT3

### ISSUE THREAD

**Issue by RyanW21** [jordanbierbrier/capstone#8]
In the System Test for Functional Requirements, test FRT3 discusses that the device should produce haptic feedback at different distances. This is not very specific right now as to what distances your device should be able to classify these sounds and produce this haptic feedback. Also, have you considered testing for your device classifying sounds at different decibel levels instead of an ambiguous distance? I think this would help standardize this test and make it less ambiguous.

@tomashetMcMaster

**Comment by UdeepShah** [comment]
The test has been altereted to a single sound played through a speaker with the different intensities placed at a distance of 0.5m.  The dB will be measured by an app on our smartphone (accuracy of +-1 dB).
