### ISSUE TITLE
Team 21 Review: Issues with System Test FRT2

### ISSUE THREAD

**Issue by snusselder** [jordanbierbrier/capstone#9]
In the System Test for Functional Requirements, test FRT2 discusses that the device will be tested in different environments. Which kind of environments specifically? Indoors? Outdoors? Will the tests be performed with different background noise or in various weather environments if performed outside? Will the testing environments change for this test or will it be the same pre-selected 5 environments for example?

@tomashetMcMaster

**Comment by UdeepShah** [comment]
The test has been updated to include 4 specified environments with different specifications.
